# Generated by Django 4.1.5 on 2023-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('my_field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
