# Generated by Django 4.1.5 on 2023-03-29 11:29

from django.db import migrations
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_field',
            field=index.models.MyAutoField(primary_key=True, serialize=False),
        ),
    ]
